feat: update k6 dependency and go version
grafana/xk6-client-prometheus-remote pull request #28
Opened 2023-07-10 14:48 UTC by fgouteroux

Hello,

Since **k6 version v0.42**  this extension **xk6-output-prometheus-remot**e is available within k6 as an experimental module.
I made this PR to update the k6 dependency version to v0.45 and go version to 1.19.

So we can do this:
```
k6 run load-testing-remote-write.js -o experimental-prometheus-rw

2023-07-27 20:49 UTC, javaducky requested changes
Hi @fgouteroux! Thank you for the update!

It looks like the `bench_test.go` no longer compiles with these changes. You can see this issue by running `go test -cover -race ./...`. Please correct the compilation issues and we'll reevaluate.

2023-07-27 20:59 UTC, javaducky commented
> So we can do this:
> 
> ```
> k6 run load-testing-remote-write.js -o experimental-prometheus-rw
> ```

@fgouteroux , there may be some confusion with this particular extension. _This_ extension (`xk6-client-prometheus-remote`) is for testing Prometheus remote write endpoints directly, i.e. testing Prometheus, DataDog, New Relic installations.

The [xk6-output-prometheus-remote](https://github.com/grafana/xk6-output-prometheus-remote) is the extension allowing k6 test metrics to be output to a Prometheus backend. It is this output extension that is invoked as an experimental module using the `-o experimental-prometheus-rw` argument to k6.

I hope this clears up any confusion on these similarly named extensions.

2023-07-27 21:02 UTC, javaducky commented
This issue would address #29.

2023-07-27 21:29 UTC, fgouteroux commented
> > So we can do this:
> 
> > 
> 
> > ```
> 
> > k6 run load-testing-remote-write.js -o experimental-prometheus-rw
> 
> > ```
> 
> 
> 
> @fgouteroux , there may be some confusion with this particular extension. _This_ extension (`xk6-client-prometheus-remote`) is for testing Prometheus remote write endpoints directly, i.e. testing Prometheus, DataDog, New Relic installations.
> 
> 
> 
> The [xk6-output-prometheus-remote](https://github.com/grafana/xk6-output-prometheus-remote) is the extension allowing k6 test metrics to be output to a Prometheus backend. It is this output extension that is invoked as an experimental module using the `-o experimental-prometheus-rw` argument to k6.
> 
> 
> 
> I hope this clears up any confusion on these similarly named extensions.
> 
> 

Yes I know and this is what I want. Testing my mimir clusters and output the result into it. I use the grafana k6 dashboard as well and we can track our tests result.

2023-07-28 09:53 UTC, fgouteroux commented
> Hi @fgouteroux! Thank you for the update!
> 
> It looks like the `bench_test.go` no longer compiles with these changes. You can see this issue by running `go test -cover -race ./...`. Please correct the compilation issues and we'll reevaluate.

@javaducky  fixed

2023-07-28 12:16 UTC, javaducky requested changes

2023-07-28 12:16 UTC, javaducky commented on go.mod
>  	github.com/oxtoacart/bpool v0.0.0-20190530202638-03653db5a59c
Please run `go mod tidy`. The requirement for `oxtoacart/bpool` is no longer necessary.

2023-07-28 12:26 UTC, javaducky approved these changes
LGTM! Thank you!

2023-07-28 12:26 UTC, merged